# Generated by Django 3.2.5 on 2021-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210722_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='presentation',
            field=models.FileField(upload_to='uploads/presentations/'),
        ),
    ]
