# Generated by Django 3.2.5 on 2021-07-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_lecture_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='mark',
            field=models.IntegerField(choices=[(5, 'Awesome'), (4, 'Very good'), (3, 'Good'), (2, 'Bad'), (1, 'Awful')]),
        ),
    ]
