# Generated by Django 3.2.5 on 2021-07-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_homework_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='answer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
