# Generated by Django 3.2.5 on 2021-07-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_comment_homework'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
