# Generated by Django 3.2.5 on 2021-07-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_homework_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
