# Generated by Django 3.2.5 on 2021-07-26 10:52

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_homework_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='presentation',
            field=models.FileField(upload_to='static/uploads/presentations/', validators=[main_app.models.validate_file_extension]),
        ),
    ]
